version: '3'

tasks:
  default:
    desc: "The default task" 
    # deps: [deploy, compose-sync]
    deps: [build-img]

  # deploy:
  #   desc: "Deploy the NixOS Cfg"
  #   deps: [ format, sb-merge, dae-merge, compose-lock, build-pm]
  #   cmds:
  #     - go run . deploy
  build-img:
    cmds:
      - clear
      - go run . build-img