version: '3'

tasks:
  default:
    desc: "The default task"
    cmds:
      - clear
      - task: docker-runner

  format:
    desc: "Format the code"
    cmds:
      - docker build -t 117503445/nix-formatter -f ./scripts/docker/formatter.Dockerfile .
      - docker run --rm -it -v $(pwd):/workspace 117503445/nix-formatter  

  build-img:
    deps: 
      - format
      - set-test-net
    cmds:
      - go run . build-img {{.CLI_ARGS}}
  
  run-vm:
    cmds:
      - go run . run-vm
  
  deploy:
    deps: 
      # - format
      - set-test-net
    cmds:
      - go run . deploy
  
  set-test-net:
    cmds:
      - go run . set-test-net
  
  docker-runner:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .
      - docker build -t 117503445/nixos-playground -f ./scripts/docker/runner.Dockerfile .
      - cd /workspace/docs/runner && docker compose up