version: '3'

tasks:
  default:
    desc: "The default task" 
    # deps: [deploy, compose-sync]
    # deps: []
    cmds:
      - clear
      - task: run-vm

  format:
    desc: "Format the code"
    cmds:
      - docker build -t 117503445/nix-formatter -f ./scripts/docker/formatter.Dockerfile .
      - docker run --rm -it -v $(pwd):/workspace 117503445/nix-formatter  

  # deploy:
  #   desc: "Deploy the NixOS Cfg"
  #   deps: [ format, sb-merge, dae-merge, compose-lock, build-pm]
  #   cmds:
  #     - go run . deploy
  build-img:
    deps: [format]
    cmds:
      - go run . build-img {{.CLI_ARGS}}
  
  run-vm:
    cmds:
      - go run . run-vm
  
  deploy:
    # deps: [format]
    cmds:
      - go run . deploy
  
  set-test-net:
    cmds:
      - go run . set-test-net