name: release

on: push

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # for debug only
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: 117503445

      - run: ./scripts/build-img-ci.sh

      - name: Generate release tag
        if: "!startsWith(github.ref, 'refs/tags/')"
        id: tag
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          files: |
            ./data/img/nixos-test.img
          tag_name: ${{ steps.tag.outputs.sha_short }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
